# Generated by Django 3.1.2 on 2020-10-19 10:29

import Blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(null=True, upload_to=Blog.models.user_directory_path),
        ),
    ]
