# Generated by Django 3.1.2 on 2020-10-20 07:48

import Blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='image1',
            field=models.FileField(null=True, upload_to=Blog.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='post',
            name='image2',
            field=models.FileField(null=True, upload_to=Blog.models.user_directory_path),
        ),
    ]
