# Generated by Django 3.1.2 on 2020-10-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_auto_20201020_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='body1',
        ),
        migrations.AddField(
            model_name='post',
            name='body2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
