# Generated by Django 3.1.2 on 2020-10-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_auto_20201020_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body3',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='head1',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='head2',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='head3',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
